sonar.projectKey=MalcolmGov_Bastion
sonar.organization=malcolmgov
sonar.sources=src
sonar.tests=tests,scripts
sonar.test.inclusions=tests/**,scripts/**
sonar.exclusions=node_modules/**,.next/**,fixtures/**,public/**
