'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import { EditorDialog } from './EditorDialog';
import { useAdminAuth } from '@/components/admin/AdminAuthProvider';
const StudioComponentRenderer=dynamic(()=>import('@/components/studio/StudioComponentRenderer').then(module=>module.StudioComponentRenderer));
import type { SectionInstance, DesignCollectionId } from '@/lib/studio/types';
interface Review {id:string;site_id:string;site_name:string;page_slug:string;title:string;version:number;status:string;requested_by:string;requested_by_name:string;decision:string;reviewer_name?:string;comment?:string;sections:SectionInstance[];layout_collection:DesignCollectionId;live?:{version:number;sections:SectionInstance[]}|null}
export function CompositionReviewQueue({clientId}:{clientId?:string}) {
  const {user,hasPerm}=useAdminAuth();
  const [reviews,setReviews]=useState<Review[]>([]),[selected,setSelected]=useState<Review|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[comment,setComment]=useState('');
  const epoch=useRef(0);
  useEffect(()=>{const epochRef=epoch;const token=++epochRef.current;setSelected(null);setError(null);setReviews([]);fetch(`/api/admin/editor/reviews${clientId ? `?clientId=${encodeURIComponent(clientId)}` : ''}`).then(async response=>{const body=await response.json();if(!response.ok)throw Error(body.error);if(token===epoch.current)setReviews(body.reviews||[]);}).catch(error=>{if(token===epoch.current)setError(error.message);});return ()=>{epochRef.current++;};},[clientId]);
  async function open(id:string){const token=epoch.current;setBusy(true);setError(null);try{const response=await fetch(`/api/admin/editor/reviews?id=${encodeURIComponent(id)}`);const body=await response.json();if(!response.ok)throw Error(body.error);if(token===epoch.current){setSelected(body.review);setComment('');}}catch(error){if(token===epoch.current)setError((error as Error).message);}finally{if(token===epoch.current)setBusy(false);}}
  async function decide(action:string){if(!selected)return;const token=epoch.current;setBusy(true);setError(null);try{const response=await fetch('/api/admin/editor/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,expectedVersion:Number(selected.version),action,comment})});const body=await response.json();if(!response.ok)throw Error(body.error);if(token===epoch.current){setReviews(items=>action==='publish'?items.filter(item=>item.id!==selected.id):items.map(item=>item.id===selected.id?{...item,status:body.status}:item));setSelected(null);}}catch(error){if(token===epoch.current)setError((error as Error).message);}finally{if(token===epoch.current)setBusy(false);}}
  return <section className="mb-6 rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900">
    <h2 className="text-lg font-semibold">Website pages for review</h2><p className="mt-1 text-sm text-slate-500">Review the saved page, approve its exact version, then publish. Editing starts a new draft and requires a fresh review.</p>
    {error&&<p role="alert" className="mt-3 text-sm text-rose-600">{error}</p>}
    {!reviews.length&&!error&&<p className="mt-4 text-sm text-slate-500">No website pages are awaiting review.</p>}
    <div className="mt-4 space-y-2">{reviews.map(review=><div key={review.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div><h3 className="font-semibold">{review.title}</h3><p className="text-xs text-slate-500">{review.site_name} · /{review.page_slug} · v{review.version} · {review.status.replace('_',' ')} · {review.requested_by_name}</p></div><button type="button" disabled={busy} onClick={()=>void open(review.id)} className="rounded-lg bg-blue-600 px-4 py-2 text-sm text-white">Review page</button></div>)}</div>
    {selected&&<EditorDialog open wide title="Review saved page" onClose={()=>setSelected(null)}><div className="mx-auto max-w-6xl rounded-2xl bg-white p-6 text-slate-900"><div className="flex justify-between gap-3"><div><h3 className="text-xl font-semibold">{selected.title} · v{selected.version}</h3><p className="text-sm text-slate-500">{selected.live?`Live v${selected.live.version} remains unchanged until publication.`:'This page has not been published.'}</p></div><button type="button" onClick={()=>setSelected(null)} disabled={busy} className="rounded-lg border px-4 py-2">Close review</button></div>
      {error&&<p role="alert" className="mt-3 text-rose-600">{error}</p>}
      <div className="mt-4 grid gap-4 lg:grid-cols-2">{selected.live&&<div><h4 className="mb-2 font-semibold">Currently published</h4><div inert className="max-h-[55vh] overflow-auto rounded-xl border pointer-events-none">{selected.live.sections.filter(section=>section.visible!==false).map(section=><StudioComponentRenderer key={section.id} section={section} collection={selected.layout_collection}/>)}</div></div>}<div className={selected.live?'':'lg:col-span-2'}><h4 className="mb-2 font-semibold">Saved version for review</h4><div inert className="max-h-[55vh] overflow-auto rounded-xl border pointer-events-none">{selected.sections.filter(section=>section.visible!==false).map(section=><StudioComponentRenderer key={section.id} section={section} collection={selected.layout_collection}/>)}</div></div></div>
      {selected.reviewer_name && <p className="mt-3 text-sm text-slate-500">Reviewed by {selected.reviewer_name}{selected.comment ? `: ${selected.comment}` : ''}</p>}
      <details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">Inspect exact saved section data</summary><pre className="mt-2 max-h-48 overflow-auto rounded-lg bg-slate-50 p-3 text-xs">{JSON.stringify(selected.sections,null,2)}</pre></details>
      <label className="mt-4 block text-sm">Review comment<textarea value={comment} onChange={event=>setComment(event.target.value)} maxLength={4000} className="mt-1 block w-full rounded-lg border p-3"/></label>
      {selected.requested_by===user?.id&&<p className="mt-2 text-sm text-amber-700">A different person must approve this version.</p>}
      <div className="mt-4 flex flex-wrap gap-3">{hasPerm('content:edit')&&<Link href={`/admin/editor?siteId=${encodeURIComponent(selected.site_id)}&pageSlug=${encodeURIComponent(selected.page_slug)}`} className="rounded-lg border px-4 py-2 text-sm">Edit page</Link>}
      {selected.status==='in_review'&&selected.requested_by!==user?.id&&<>{hasPerm('content:approve')&&<button disabled={busy} onClick={()=>void decide('approve')} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm text-white">Approve v{selected.version}</button>}{hasPerm('content:request_changes')&&<button disabled={busy} onClick={()=>void decide('request_changes')} className="rounded-lg border px-4 py-2 text-sm">Request changes</button>}</>}
      {selected.status==='approved'&&hasPerm('content:publish')&&<button disabled={busy} onClick={()=>void decide('publish')} className="rounded-lg bg-blue-600 px-4 py-2 text-sm text-white">Publish approved v{selected.version}</button>}</div>
    </div></EditorDialog>}
  </section>;
}
